import { useEffect, useState } from "react";
import { Link, Navigate, useParams } from "react-router";
import { ArrowLeft, BadgeCheck, CheckSquare2, FileSignature, Printer, ShieldCheck } from "lucide-react";
import { useAdmin } from "../context/AdminContext";
import { fetchAllMatrimonials, MatrimonialProfile, MatrimonialReference } from "../lib/matrimonialStore";
import { BEHAVIOR_QUESTIONS } from "../lib/matrimonialCompatibility";

const GREEN="#1a4d2e", GOLD="#c8a04a";

export function AdminMatrimonialPrintPage(){
  const {isAdmin,role}=useAdmin();
  const allowed=["admin","super_admin","welfare_manager","matrimonial_manager"].includes(String(role||""));
  const {id}=useParams();
  const [profile,setProfile]=useState<MatrimonialProfile|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  useEffect(()=>{if(!isAdmin||!allowed||!id)return;(async()=>{try{const r=await fetchAllMatrimonials(1,100);const p=r.data.find(x=>x.id===id);if(!p)throw new Error("Candidate profile not found.");setProfile(p);}catch(e:any){setError(e?.message||"Could not load printable form.");}finally{setLoading(false);}})();},[id,isAdmin,allowed]);
  if(!isAdmin||!allowed)return <Navigate to="/admin" replace/>;
  if(loading)return <div style={{padding:60,textAlign:"center"}}>Loading official form...</div>;
  if(error||!profile)return <div style={{padding:50,color:"#b91c1c"}}>{error||"Profile not found."}</div>;
  const d=profile.profileData||{}, pref=profile.preferenceData||{}, privacy=profile.privacyData||{}, behavior=d.behavior||{};
  const references=(Array.isArray(d.references)?d.references:[]) as MatrimonialReference[];
  const timeline=d.marriageTimeline||formatTimeline(d.marriageTimelineValue,d.marriageTimelineUnit,d.marriageTimelineFlexibility);
  return <div style={{background:"#eee",minHeight:"100vh",padding:"20px",fontFamily:"Arial, sans-serif"}}>
    <div className="print-actions" style={{maxWidth:900,margin:"0 auto 12px",display:"flex",justifyContent:"space-between",gap:8}}><Link to="/admin/matrimonial" style={btn}><ArrowLeft size={14}/>Control Center</Link><button onClick={()=>window.print()} style={primary}><Printer size={14}/>Print Form + Undertakings / Save PDF</button></div>
    <article style={sheet}>
      <header style={{borderBottom:`3px solid ${GOLD}`,paddingBottom:16,marginBottom:20,display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start"}}><div><div style={{color:GREEN,fontSize:24,fontWeight:800}}>Anjuman-e-Araian Faisalabad</div><div style={{fontSize:14,color:"#555",marginTop:3}}>Confidential Matrimonial Candidate Form</div><div style={{fontSize:10,color:"#888",marginTop:5}}>Authorized private matching document · not for public distribution</div></div><div style={{textAlign:"right"}}><div style={{fontWeight:800,color:GREEN}}>{profile.profileCode}</div><div style={{fontSize:10,color:"#777",marginTop:4}}>Printed: {new Date().toLocaleString()}</div></div></header>
      <div style={{background:"#f5f8f6",border:`1px solid #d9e6dd`,padding:10,borderRadius:6,fontSize:10,color:"#56615a",marginBottom:18}}><ShieldCheck size={13} style={{verticalAlign:"-3px",marginRight:5}}/>Contains private candidate and reference information. Handle only within the authorized matrimonial process and according to recorded candidate/guardian consent.</div>
      <Section title="Candidate Identification"><Grid><Item k="Full Name" v={profile.name}/><Item k="Candidate Email" v={profile.email}/><Item k="Private Contact" v={profile.contact}/><Item k="Managed For" v={profile.relationToCandidate}/><Item k="Gender" v={profile.gender}/><Item k="Age" v={profile.age}/><Item k="Date of Birth" v={profile.dateOfBirth}/><Item k="Height" v={profile.heightCm?`${profile.heightCm} cm`:""}/><Item k="Marital Status" v={profile.maritalStatus}/><Item k="Candidate Consent" v={profile.candidateConsent?"Recorded":"Not recorded"}/></Grid></Section>
      <Section title="Location, Education & Career"><Grid><Item k="Country" v={profile.country}/><Item k="Province / State" v={profile.province}/><Item k="City" v={profile.city}/><Item k="Nationality" v={profile.nationality}/><Item k="Residence / Visa" v={profile.residenceStatus}/><Item k="Education" v={profile.education}/><Item k="Profession" v={profile.profession}/><Item k="Employment Type" v={profile.employmentType||d.employmentType}/><Item k="Employer Type" v={profile.employerType||d.employerType}/><Item k="Income Band" v={profile.incomeBand||d.incomeBand}/><Item k="Currency" v={profile.currency}/></Grid></Section>
      <Section title="Family, Lifestyle & Intentions"><Grid><Item k="Family Setup" v={d.familySetup}/><Item k="Sect" v={d.sect}/><Item k="Languages" v={Array.isArray(d.languages)?d.languages.join(", "):d.languages}/><Item k="Hobbies" v={d.hobbies}/><Item k="Marriage Timeline" v={timeline}/><Item k="Timeline Normalized" v={d.marriageTimelineDays?`${d.marriageTimelineDays} days`:""}/><Item k="Timeline Flexibility" v={d.marriageTimelineFlexibility}/><Item k="Relocation" v={d.relocation}/></Grid><Text k="Family Notes / Background" v={d.familyNotes||profile.familyBackground}/></Section>
      {Object.values(behavior).some((v:any)=>Number(v)>0)&&<Section title="Lifestyle & Behavior Compatibility Answers"><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:"7px 14px"}}>{BEHAVIOR_QUESTIONS.map(q=><BehaviorItem key={q.key} label={q.label} value={behavior[q.key]}/>)}</div><div style={{fontSize:8,color:"#777",marginTop:8,lineHeight:1.5}}>Self-reported lifestyle/communication preferences used as soft compatibility signals. They are not a psychological diagnosis or suitability guarantee.</div></Section>}
      <Section title="Partner Preferences"><Pref label="Age" data={pref.age}/><Pref label="Height" data={pref.height}/><Pref label="Education" data={pref.education}/><Pref label="Profession" data={pref.profession}/><Pref label="Country" data={pref.country}/><Pref label="City" data={pref.city}/><Pref label="Marital Status" data={pref.maritalStatus}/><Pref label="Residence Status" data={pref.residenceStatus}/><Pref label="Family Setup" data={pref.familySetup}/><Pref label="Sect" data={pref.sect}/><Pref label="Relocation" data={pref.relocation}/><Pref label="Income" data={pref.income}/><Text k="Other Expectations" v={pref.notes||profile.requirements}/></Section>
      <Section title="References / Verification">{references.length?<div style={{display:"grid",gap:8}}>{references.map((r,index)=><div key={index} style={{border:"1px solid #e4e7e5",borderRadius:6,padding:9,pageBreakInside:"avoid"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><strong style={{color:GREEN,fontSize:10}}>Reference {index+1}: {r.name}</strong>{r.isMember&&<span style={{display:"inline-flex",alignItems:"center",gap:3,background:"#e7f7ec",color:"#166534",borderRadius:14,padding:"3px 6px",fontSize:8,fontWeight:800}}><BadgeCheck size={10}/>Anjuman Member {r.memberNo||""}</span>}</div><Grid><Item k="Profession" v={r.profession}/><Item k="Mobile" v={r.phone}/><Item k="City" v={r.city}/><Item k="Address / Area" v={r.address}/><Item k="Member Record" v={r.isMember?(r.memberName||r.name):"Non-member reference"}/></Grid></div>)}</div>:<div style={{fontSize:10,color:"#a16207",background:"#fff7ed",padding:8,borderRadius:6}}>References have not yet been recorded. Minimum two references are required on the updated workflow.</div>}</Section>
      <Section title="Privacy, Verification & Workflow"><Grid><Item k="Profile Status" v={profile.status}/><Item k="Payment Status" v={profile.paymentStatus}/><Item k="Verification" v={profile.verificationStatus}/><Item k="Profile & Match Readiness" v={`${profile.profileCompleteness||0}%`}/><Item k="Private Matching" v={profile.showOnPortal?"Enabled":"Disabled"}/><Item k="Photo Privacy" v={privacy.photoVisibility}/><Item k="Contact Privacy" v={privacy.contactVisibility}/><Item k="Application Source" v={profile.applicationSource}/><Item k="Last Profile Email" v={profile.lastProfileEmailAt?new Date(profile.lastProfileEmailAt).toLocaleString():"Not sent"}/></Grid><Text k="Admin / Manager Note" v={profile.adminNote}/></Section>
      {profile.photoUrl&&<Section title="Candidate Photo (Confidential)"><img src={profile.photoUrl} alt="Candidate" style={{width:130,height:160,objectFit:"cover",border:"1px solid #ddd",borderRadius:4}}/></Section>}
      <footer style={footer}><span>Confidential · Anjuman-e-Araian Faisalabad Matrimonial Service</span><span>{profile.profileCode}</span></footer>
    </article>

    <Annexure title="Annexure A · Candidate / Guardian Information & Consent Declaration" code={profile.profileCode}>
      <Lead icon={<FileSignature size={19}/>} text="This annexure records the candidate/guardian's acknowledgement about the information supplied to the matrimonial service."/>
      <Clause n="1" text="I confirm that I am the adult candidate, or I am authorized by the adult candidate to submit/manage this profile and participate in the private matching process."/>
      <Clause n="2" text="I confirm that the information, documents, photographs, family details, education, employment and marital-status information supplied by me/us is, to the best of my/our knowledge, true and not deliberately misleading."/>
      <Clause n="3" text="I will promptly inform the matrimonial manager if any material information changes, including marital status, residence, contact information or availability for matching."/>
      <Clause n="4" text="I understand that compatibility percentages are computer-assisted decision support based on supplied profile/preferences. They are not a psychological assessment, background verification, recommendation or guarantee of marriage suitability or success."/>
      <Clause n="5" text="I consent to the use of the supplied information for private matching, committee/manager review and consent-controlled introductions in accordance with the selected privacy settings."/>
      <SignatureBlock/>
    </Annexure>

    <Annexure title="Annexure B · Matching, Introduction, Privacy & Responsibility Acknowledgement" code={profile.profileCode}>
      <Lead icon={<ShieldCheck size={19}/>} text="The service facilitates matching and introductions. Final verification, communication and decisions remain with the candidates and families."/>
      <Check text="Before consent, the other side may receive only an anonymized profile code, compatibility percentage and privacy-permitted basic profile information."/>
      <Check text="Name, photograph, phone/contact and sensitive information are released only according to the recorded consent workflow and privacy permissions."/>
      <Check text="The candidate/family is responsible for independently verifying identity, age, marital status, family background, education, employment/business, residence/visa status, financial claims and any other material fact before relying on it."/>
      <Check text="The service does not conduct or guarantee police, legal, financial, medical, immigration, employment or other specialist due diligence unless a specific verification is expressly recorded in writing."/>
      <Check text="Meetings, travel, gifts, loans, payments, engagement/marriage arrangements and any private communication or transaction between the parties are their own decisions and responsibility. No payment should be made to another candidate/family merely because a match was introduced by the service."/>
      <Check text="Either side may decline an introduction without receiving the other side's private contact details. A match score or acceptance of an introduction is not acceptance of a marriage proposal."/>
      <Check text="I understand that the service may suspend a profile or introduction where consent, identity, conduct or information appears unreliable, incomplete or inconsistent."/>
      <div style={legalNote}>This acknowledgement is intended to clarify the administrative matching service and does not exclude any legal responsibility that cannot lawfully be excluded. For a binding legal waiver or indemnity, the organization should have the final wording reviewed by its Pakistan-qualified legal adviser.</div>
      <SignatureBlock/>
    </Annexure>

    <Annexure title="Annexure C · Verification & Introduction Record" code={profile.profileCode}>
      <Lead icon={<CheckSquare2 size={19}/>} text="Office checklist for documenting what was actually checked and how consent/introduction was recorded."/>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:14}}>{[
        "Candidate / guardian consent recorded","Candidate photo on file","Identity document checked (if applicable)","Two references recorded","Education claim checked (if applicable)","Employment/business claim checked (if applicable)","Payment / service fee status recorded","Privacy settings explained","Match percentage shown to client","Other side reviewed anonymized basics","Consent method documented","Contact/photo release follows privacy settings",
      ].map(x=><div key={x} style={checkRow}>□ {x}</div>)}</div>
      <div style={{marginTop:18}}><Line label="Verification / consent notes" wide/><Line label="Match / request reference"/><Line label="Consent method (portal / phone / office / signed form / family meeting)" wide/><Line label="Date & time"/><Line label="Matrimonial manager / authorized officer"/><Line label="Officer signature"/></div>
      <div style={{marginTop:18,padding:11,border:`1px solid ${GOLD}`,background:"#fff9ec",fontSize:9,lineHeight:1.55,color:"#655b43"}}><strong>Record rule:</strong> tick or complete only items actually checked. A blank item must not be treated as verified.</div>
    </Annexure>

    <style>{`@media print{body{background:white!important}.print-actions{display:none!important}.print-sheet{box-shadow:none!important;max-width:none!important;padding:20px 25px!important}.annexure{page-break-before:always;box-shadow:none!important;max-width:none!important;padding:20px 25px!important}@page{size:A4;margin:12mm}}@media(max-width:700px){.annexure-grid{grid-template-columns:1fr!important}}`}</style>
  </div>;
}
function formatTimeline(value:any,unit:any,flexibility:any){if(!value)return "";const n=Number(value);const u=String(unit||"months");return `Within ${n} ${u}${flexibility==="flexible"?" (flexible)":""}`;}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={{marginBottom:20,pageBreakInside:"avoid"}}><h2 style={{fontSize:13,color:GREEN,borderBottom:"1px solid #ddd",paddingBottom:5,margin:"0 0 10px"}}>{title}</h2>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:"8px 14px",marginTop:7}}>{children}</div>}
function Item({k,v}:{k:string;v:any}){if(v===undefined||v===null||String(v).trim()==="")return null;return <div><div style={{fontSize:8,color:"#888",textTransform:"uppercase",fontWeight:700}}>{k}</div><div style={{fontSize:10,color:"#222",marginTop:2,wordBreak:"break-word"}}>{String(v).replace(/_/g," ")}</div></div>}
function BehaviorItem({label,value}:{label:string;value:any}){const n=Number(value||0);if(n<1||n>5)return null;return <div style={{border:"1px solid #eee",borderRadius:5,padding:6}}><div style={{fontSize:8,color:"#777",fontWeight:700}}>{label}</div><div style={{fontSize:10,color:GREEN,fontWeight:800,marginTop:2}}>{n}/5</div></div>}
function Text({k,v}:{k:string;v:any}){if(!v)return null;return <div style={{marginTop:9}}><div style={{fontSize:8,color:"#888",textTransform:"uppercase",fontWeight:700}}>{k}</div><div style={{fontSize:10,lineHeight:1.55,color:"#333",whiteSpace:"pre-wrap",marginTop:2}}>{String(v)}</div></div>}
function Pref({label,data}:{label:string;data:any}){if(!data||typeof data!=="object")return null;const primary=Array.isArray(data.primary)?data.primary.join(", "):"",secondary=Array.isArray(data.secondary)?data.secondary.join(", "):"",acceptable=Array.isArray(data.acceptable)?data.acceptable.join(", "):"";const range=data.min||data.max?`${data.min||"Any"} – ${data.max||"Any"}`:"";const income=data.minimum?`Minimum ${data.minimum}`:"";if(!primary&&!secondary&&!acceptable&&!range&&!income)return null;return <div style={{display:"grid",gridTemplateColumns:"130px 1fr",gap:8,borderBottom:"1px dotted #ddd",padding:"5px 0",fontSize:9}}><strong style={{color:GREEN}}>{label}</strong><span>{range||income||[primary&&`Primary: ${primary}`,secondary&&`Secondary: ${secondary}`,acceptable&&`Acceptable: ${acceptable}`].filter(Boolean).join(" · ")} {data.importance?`[${String(data.importance).replace(/_/g," ")}]`:""}</span></div>}
function Annexure({title,code,children}:{title:string;code?:string;children:React.ReactNode}){return <article className="annexure print-sheet" style={sheet}><header style={{borderBottom:`3px solid ${GOLD}`,paddingBottom:12,marginBottom:16,display:"flex",justifyContent:"space-between",gap:12}}><div><div style={{fontSize:20,color:GREEN,fontWeight:900}}>Anjuman-e-Araian Faisalabad</div><h1 style={{fontSize:15,margin:"5px 0 0",color:"#333"}}>{title}</h1></div><strong style={{color:GREEN,fontSize:10}}>{code}</strong></header>{children}<footer style={footer}><span>Confidential Matrimonial Service Annexure</span><span>{code}</span></footer></article>}
function Lead({icon,text}:{icon:React.ReactNode;text:string}){return <div style={{display:"flex",gap:9,alignItems:"flex-start",background:"#f2f8f4",border:"1px solid #d9e7dd",borderRadius:8,padding:11,color:GREEN,fontSize:10,lineHeight:1.6}}><span style={{flexShrink:0,color:GOLD}}>{icon}</span><strong>{text}</strong></div>}
function Clause({n,text}:{n:string;text:string}){return <div style={{display:"grid",gridTemplateColumns:"25px 1fr",gap:8,marginTop:11,fontSize:10,lineHeight:1.6,color:"#333"}}><span style={{width:22,height:22,borderRadius:"50%",background:GREEN,color:"white",display:"grid",placeItems:"center",fontSize:9,fontWeight:900}}>{n}</span><span>{text}</span></div>}
function Check({text}:{text:string}){return <div style={{display:"grid",gridTemplateColumns:"20px 1fr",gap:7,marginTop:10,fontSize:10,lineHeight:1.55,color:"#333"}}><span style={{fontSize:15,color:GREEN}}>□</span><span>{text}</span></div>}
function SignatureBlock(){return <div className="annexure-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"20px 28px",marginTop:28}}><Line label="Candidate / Guardian Name"/><Line label="Relationship to Candidate"/><Line label="CNIC / ID No. (if recorded for verification)"/><Line label="Mobile / Contact"/><Line label="Signature / Thumb Impression"/><Line label="Date"/><Line label="Witness / Authorized Officer"/><Line label="Officer Signature & Date"/></div>}
function Line({label,wide=false}:{label:string;wide?:boolean}){return <div style={{gridColumn:wide?"1 / -1":undefined,marginTop:14}}><div style={{borderBottom:"1px solid #555",height:20}}/><div style={{fontSize:8,color:"#777",marginTop:3}}>{label}</div></div>}
const sheet:React.CSSProperties={maxWidth:900,margin:"0 auto 20px",background:"white",padding:"38px 42px",boxShadow:"0 5px 25px rgba(0,0,0,.12)"};
const footer:React.CSSProperties={borderTop:"1px solid #ddd",marginTop:26,paddingTop:14,fontSize:9,color:"#777",display:"flex",justifyContent:"space-between"};
const checkRow:React.CSSProperties={border:"1px solid #e5e7e5",borderRadius:6,padding:8,fontSize:9,color:"#3f4a43"};
const legalNote:React.CSSProperties={marginTop:16,background:"#f8f5ef",border:"1px solid #e4ded1",borderRadius:7,padding:10,fontSize:8.5,lineHeight:1.55,color:"#686257"};
const btn:React.CSSProperties={display:"inline-flex",alignItems:"center",gap:5,background:"white",color:GREEN,border:"1px solid #ccd8cf",borderRadius:7,padding:"9px 12px",textDecoration:"none",fontSize:11,fontWeight:800};
const primary:React.CSSProperties={...btn,background:GREEN,color:"white",cursor:"pointer"};