import { useEffect, useMemo, useState } from "react";
import { Link, Navigate } from "react-router";
import { ArrowLeft, BadgeCheck, CheckCircle, Eye, EyeOff, FileText, HeartHandshake, History, Plus, Printer, RefreshCw, Search, ShieldCheck, Star, X, XCircle } from "lucide-react";
import { useAdmin } from "../context/AdminContext";
import {
  adminReviewMatchRequest,
  fetchAdminMatchRequests,
  fetchAllMatrimonials,
  fetchMatrimonialAudit,
  fetchMatrimonialManager,
  MatrimonialProfile,
  MatrimonialStatus,
  updateMatrimonial,
} from "../lib/matrimonialStore";

const GREEN="#1a4d2e", GOLD="#c8a04a";

export function AdminMatrimonialPage(){
  const {isAdmin,role}=useAdmin();
  const allowed=["admin","super_admin","welfare_manager","matrimonial_manager"].includes(String(role||""));
  const [tab,setTab]=useState<"profiles"|"requests">("profiles");
  const [profiles,setProfiles]=useState<MatrimonialProfile[]>([]);
  const [requests,setRequests]=useState<any[]>([]);
  const [manager,setManager]=useState<any>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [success,setSuccess]=useState("");
  const [search,setSearch]=useState("");
  const [status,setStatus]=useState<"all"|MatrimonialStatus>("all");
  const [viewing,setViewing]=useState<MatrimonialProfile|null>(null);
  const [auditFor,setAuditFor]=useState<MatrimonialProfile|null>(null);
  const [auditRows,setAuditRows]=useState<any[]>([]);
  const [auditLoading,setAuditLoading]=useState(false);
  const [reviewing,setReviewing]=useState<string|null>(null);

  const load=async()=>{setLoading(true);setError("");try{const [p,r,m]=await Promise.all([fetchAllMatrimonials(1,100),fetchAdminMatchRequests(),fetchMatrimonialManager().catch(()=>null)]);setProfiles(p.data);setRequests(r);setManager(m);}catch(e:any){setError(e?.message||"Matrimonial control center could not be loaded.");}finally{setLoading(false);}};
  useEffect(()=>{if(isAdmin&&allowed)void load();},[isAdmin,allowed]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return profiles.filter(p=>(status==="all"||p.status===status)&&(!q||`${p.profileCode||""} ${p.name||""} ${p.city} ${p.country||""} ${p.education} ${p.profession} ${p.contact||""}`.toLowerCase().includes(q)));},[profiles,search,status]);
  if(!isAdmin)return <Navigate to="/admin" replace/>;
  if(!allowed)return <Navigate to="/admin" replace/>;

  const quick=async(p:MatrimonialProfile,changes:Partial<MatrimonialProfile>)=>{setError("");setSuccess("");try{await updateMatrimonial(p.id,changes);setSuccess(`${p.profileCode} updated.`);await load();}catch(e:any){setError(e?.message||"Update could not be saved.");}};
  const openAudit=async(p:MatrimonialProfile)=>{setAuditFor(p);setAuditRows([]);setAuditLoading(true);setError("");try{setAuditRows(await fetchMatrimonialAudit(p.id));}catch(e:any){setError(e?.message||"Audit history could not be loaded.");}finally{setAuditLoading(false);}};
  const review=async(r:any,action:"forward"|"reject"|"close")=>{setReviewing(r.id);setError("");setSuccess("");try{await adminReviewMatchRequest(r.id,action);setSuccess(action==="forward"?"Interest forwarded for candidate/guardian consent.":action==="reject"?"Interest rejected.":"Interest closed.");await load();}catch(e:any){setError(e?.message||"Request could not be updated.");}finally{setReviewing(null);}};

  const counts={all:profiles.length,pending:profiles.filter(p=>p.status==="pending").length,approved:profiles.filter(p=>p.status==="approved").length,verified:profiles.filter(p=>p.verificationStatus==="committee_verified"||p.verificationStatus==="identity_checked").length,active:profiles.filter(p=>p.status==="approved"&&p.showOnPortal&&p.isActive!==false).length};

  return <div style={{minHeight:"100vh",background:"#f8f5ef",fontFamily:"Lato, sans-serif"}}>
    <header style={{background:GREEN,borderBottom:`4px solid ${GOLD}`,color:"white",padding:"18px 24px"}}><div style={{maxWidth:1380,margin:"0 auto",display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><h1 style={{margin:0,fontFamily:"'Playfair Display', serif",fontSize:25}}>Matrimonial Control Center</h1><p style={{margin:"4px 0 0",opacity:.78,fontSize:11}}>Private candidate registry, two-way compatibility, consent, verification and audit</p></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button onClick={()=>void load()} style={ghost}><RefreshCw size={13}/>Refresh</button><Link to="/admin/finance" style={{...ghost,textDecoration:"none"}}>Finance Verification</Link><Link to="/admin" style={{...ghost,textDecoration:"none"}}><ArrowLeft size={13}/>Main Admin</Link></div></div></header>
    <main style={{maxWidth:1380,margin:"0 auto",padding:"24px 20px 60px"}}>
      {manager&&<div style={{background:"#eef6ff",border:"1px solid #cfe4fb",color:"#315f7d",borderRadius:10,padding:11,marginBottom:14,fontSize:11,lineHeight:1.6}}><ShieldCheck size={14} style={{verticalAlign:"-3px",marginRight:5}}/><strong>Internal Matrimonial Manager:</strong> {manager.name}. Notifications are configured as <strong>{String(manager.notificationMode||"digest")}</strong>; manager contact is not exposed publicly and the system should not rely on repeated direct calls/messages for routine matching.</div>}
      {error&&<Notice bg="#fee2e2" color="#b91c1c">{error}</Notice>}{success&&<Notice bg="#dcfce7" color="#166534">{success}</Notice>}
      <div className="mat-stats" style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:10,marginBottom:16}}><Stat t="All Profiles" v={counts.all}/><Stat t="Pending Review" v={counts.pending}/><Stat t="Approved" v={counts.approved}/><Stat t="Identity / Committee Checked" v={counts.verified}/><Stat t="Active for Matching" v={counts.active}/></div>
      <div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap",marginBottom:16}}><div style={{display:"flex",gap:8}}><button onClick={()=>setTab("profiles")} style={tabBtn(tab==="profiles")}>Candidate Registry ({profiles.length})</button><button onClick={()=>setTab("requests")} style={tabBtn(tab==="requests")}>Interests & Consent ({requests.length})</button></div><Link to="/admin/matrimonial/new" style={primaryLink}><Plus size={14}/>Add Client / Candidate</Link></div>

      {loading?<div style={{padding:50,textAlign:"center",color:"#777"}}>Loading confidential matrimonial records...</div>:tab==="profiles"?<section style={card}>
        <div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",alignItems:"center",marginBottom:13}}><div><h2 style={sectionTitle}>Private Candidate Registry</h2><p style={sub}>"Matching Enabled" means the anonymous profile may enter the private matching engine. It never means a public name, photo or contact listing.</p></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><div style={{position:"relative"}}><Search size={14} color="#999" style={{position:"absolute",left:10,top:10}}/><input style={{...input,paddingLeft:31,width:250}} placeholder="Search code, name, city, profession..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select style={input} value={status} onChange={e=>setStatus(e.target.value as any)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div></div>
        <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1180}}><thead><tr style={{background:"#f7f3eb"}}>{["Profile","Candidate","Location / Work","Completeness","Verification","Status","Payment","Matching","Actions"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(p=><tr key={p.id} style={{borderTop:"1px solid #eee"}}><td style={td}><strong style={{color:GREEN}}>{p.profileCode}</strong><small style={small}>{p.relationToCandidate||"Self"} · {p.applicationSource?.replace(/_/g," ")||"legacy"}</small></td><td style={td}><div style={{display:"flex",gap:8,alignItems:"center"}}>{p.photoUrl?<img src={p.photoUrl} alt="" style={{width:40,height:40,objectFit:"cover",borderRadius:"50%"}}/>:<div style={{width:40,height:40,borderRadius:"50%",background:"#eef5f0"}}/>}<div><b>{p.name||"Candidate"}</b><small style={small}>{p.gender} · {p.age} yrs</small></div></div></td><td style={td}>{p.city}{p.country&&p.country!=="Pakistan"?`, ${p.country}`:""}<small style={small}>{p.education} · {p.profession}</small></td><td style={td}><Badge text={`${p.profileCompleteness||0}%`} good={(p.profileCompleteness||0)>=75}/></td><td style={td}><Badge text={(p.verificationStatus||"unverified").replace(/_/g," ")} good={["identity_checked","committee_verified"].includes(p.verificationStatus||"")}/></td><td style={td}><Badge text={p.status||"pending"} good={p.status==="approved"}/></td><td style={td}><Badge text={p.paymentStatus||"pending"} good={["received","verified"].includes(p.paymentStatus||"")}/></td><td style={td}><button onClick={()=>void quick(p,{showOnPortal:!p.showOnPortal})} style={mini(p.showOnPortal?GREEN:"#666")}>{p.showOnPortal?<Eye size={12}/>:<EyeOff size={12}/>} {p.showOnPortal?"Enabled":"Disabled"}</button></td><td style={td}><div style={{display:"flex",gap:5,flexWrap:"wrap"}}><button onClick={()=>setViewing(p)} style={mini(GREEN)}><Eye size={12}/>View</button><Link to={`/admin/matrimonial/edit/${p.id}`} style={{...mini("#315fba"),textDecoration:"none"}}>Edit</Link><Link to={`/admin/matrimonial/print/${p.id}`} target="_blank" style={{...mini("#6b4f0a"),textDecoration:"none"}}><Printer size={12}/>Print</Link><button onClick={()=>void openAudit(p)} style={mini("#555")}><History size={12}/>Audit</button><button onClick={()=>void quick(p,{isFeatured:!p.isFeatured})} style={mini(p.isFeatured?"#946b08":"#777")}><Star size={12}/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div style={{padding:35,textAlign:"center",color:"#999"}}>No candidate profiles in this view.</div>}</div>
      </section>:<section style={card}><div style={{marginBottom:15}}><h2 style={sectionTitle}>Interest & Consent Queue</h2><p style={sub}>The score shown here is the stored two-way compatibility result from the matching engine. Forwarding reveals no contact; it only asks the target side to review the anonymized interest.</p></div>{requests.length?<div style={{display:"grid",gap:12}}>{requests.map(r=><article key={r.id} style={{border:"1px solid #e7e2d8",borderRadius:11,padding:15}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><strong style={{color:GREEN}}>{r.requester?.profileCode}</strong> <span style={{color:"#aaa"}}>→</span> <strong style={{color:GREEN}}>{r.target?.profileCode}</strong><small style={small}>{new Date(r.createdAt).toLocaleString()}</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><Badge text={`${r.mutualScore??0}% mutual`} good={(r.mutualScore??0)>=70}/><Badge text={`confidence ${r.scoreConfidence??0}%`} good={(r.scoreConfidence??0)>=70}/><Badge text={String(r.status).replace(/_/g," ")} good={r.status==="accepted"}/></div></div><div className="request-pair" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:11}}><ProfileBox title="Requester" p={r.requester}/><ProfileBox title="Target" p={r.target}/></div>{r.requesterMessage&&<div style={{background:"#f8f5ef",borderRadius:7,padding:9,marginTop:9,fontSize:10,color:"#555"}}><b>Request note:</b> {r.requesterMessage}</div>}<div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:11}}>{r.status==="pending_admin"&&<><button disabled={reviewing===r.id} onClick={()=>void review(r,"forward")} style={action(GREEN)}><CheckCircle size={12}/>Forward for Consent</button><button disabled={reviewing===r.id} onClick={()=>void review(r,"reject")} style={action("#b91c1c")}><XCircle size={12}/>Reject</button></>}{!["closed","rejected"].includes(r.status)&&<button disabled={reviewing===r.id} onClick={()=>void review(r,"close")} style={action("#666")}><X size={12}/>Close</button>}</div></article>)}</div>:<div style={{padding:35,textAlign:"center",color:"#999"}}><HeartHandshake size={28}/><p>No interest requests yet.</p></div>}</section>}
    </main>

    {viewing&&<Modal title={`${viewing.profileCode} · Confidential Profile`} onClose={()=>setViewing(null)}><div style={{display:"grid",gap:11}}><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}><Info k="Name" v={viewing.name}/><Info k="Managed For" v={viewing.relationToCandidate}/><Info k="Consent" v={viewing.candidateConsent?"Recorded":"Missing"}/><Info k="Country / City" v={`${viewing.country||"Pakistan"} · ${viewing.city}`}/><Info k="Education" v={viewing.education}/><Info k="Profession" v={viewing.profession}/><Info k="Private Contact" v={viewing.contact}/><Info k="Verification" v={viewing.verificationStatus}/><Info k="Matching" v={viewing.showOnPortal?"Enabled":"Disabled"}/></div>{viewing.familyBackground&&<Text title="Family Background" value={viewing.familyBackground}/>} {viewing.requirements&&<Text title="Partner Requirements" value={viewing.requirements}/>}<div style={{display:"flex",gap:7,flexWrap:"wrap"}}><Link to={`/admin/matrimonial/edit/${viewing.id}`} style={primaryLink}>Edit Full Profile</Link><Link to={`/admin/matrimonial/print/${viewing.id}`} target="_blank" style={secondaryLink}><FileText size={12}/>Official Form</Link><button onClick={()=>void openAudit(viewing)} style={secondaryButton}><History size={12}/>Audit</button></div></div></Modal>}
    {auditFor&&<Modal title={`Audit History · ${auditFor.profileCode}`} onClose={()=>{setAuditFor(null);setAuditRows([])}} wide><div style={{background:"#f0f7f3",padding:10,borderRadius:8,color:"#59655d",fontSize:10,lineHeight:1.6,marginBottom:10}}>Append-only history of profile, consent, matching and manager actions. Source IP is visible only to authorized administrators.</div>{auditLoading?<div style={{padding:25,textAlign:"center"}}>Loading audit...</div>:auditRows.length?<div style={{display:"grid",gap:7}}>{auditRows.map(r=><div key={r.id} style={{border:"1px solid #eee",borderRadius:8,padding:9,fontSize:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><strong style={{color:GREEN,textTransform:"capitalize"}}>{String(r.action).replace(/_/g," ")}</strong><span style={{color:"#888"}}>{new Date(r.createdAt).toLocaleString()}</span></div><div style={{color:"#777",marginTop:3}}>Actor: {r.actorName||"system"} · {r.actorRole||"system"} · IP: {r.ipAddress||"not recorded"}</div></div>)}</div>:<div style={{padding:25,textAlign:"center",color:"#999"}}>No audit entries yet.</div>}</Modal>}
    <style>{`@media(max-width:900px){.mat-stats{grid-template-columns:repeat(2,1fr)!important}.request-pair{grid-template-columns:1fr!important}}`}</style>
  </div>;
}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div style={{position:"fixed",inset:0,zIndex:10000,background:"rgba(0,0,0,.58)",display:"grid",placeItems:"center",padding:14}}><div style={{width:wide?"min(900px,96vw)":"min(680px,96vw)",maxHeight:"90vh",overflowY:"auto",background:"white",borderRadius:13}}><div style={{position:"sticky",top:0,zIndex:2,background:"white",padding:"13px 16px",borderBottom:"1px solid #eee",display:"flex",justifyContent:"space-between",gap:8}}><h3 style={{margin:0,color:GREEN,fontFamily:"'Playfair Display', serif"}}>{title}</h3><button onClick={onClose} style={{border:0,background:"transparent",cursor:"pointer"}}><X size={18}/></button></div><div style={{padding:16}}>{children}</div></div></div>}
function Stat({t,v}:{t:string;v:number}){return <div style={{background:"white",border:"1px solid #e8e3da",borderRadius:10,padding:12}}><div style={{color:"#777",fontSize:9}}>{t}</div><strong style={{display:"block",color:GREEN,fontSize:23,marginTop:2}}>{v}</strong></div>}
function Badge({text,good}:{text:string;good:boolean}){return <span style={{background:good?"#dcfce7":"#f3f4f6",color:good?"#166534":"#555",padding:"4px 7px",borderRadius:18,fontSize:9,fontWeight:800,textTransform:"capitalize",whiteSpace:"nowrap"}}>{text}</span>}
function ProfileBox({title,p}:{title:string;p:any}){return <div style={{background:"#faf9f6",borderRadius:8,padding:10}}><div style={{fontSize:9,color:"#888",fontWeight:800,textTransform:"uppercase"}}>{title}</div><div style={{color:GREEN,fontWeight:900,fontSize:11,marginTop:3}}>{p?.profileCode}</div><div style={{color:"#555",fontSize:10,marginTop:3}}>{p?.gender} · {p?.age} · {p?.city}</div><div style={{color:"#777",fontSize:9,marginTop:3}}>{p?.education} · {p?.profession}</div></div>}
function Info({k,v}:{k:string;v:any}){return <div style={{background:"#faf9f6",borderRadius:7,padding:8}}><div style={{fontSize:8,color:"#999",textTransform:"uppercase",fontWeight:800}}>{k}</div><div style={{fontSize:10,color:"#333",marginTop:2}}>{v||"-"}</div></div>}
function Text({title,value}:{title:string;value:string}){return <div><strong style={{color:GREEN,fontSize:10}}>{title}</strong><p style={{fontSize:10,color:"#666",lineHeight:1.6,whiteSpace:"pre-wrap",margin:"4px 0"}}>{value}</p></div>}
function Notice({bg,color,children}:{bg:string;color:string;children:React.ReactNode}){return <div style={{background:bg,color,borderRadius:8,padding:10,marginBottom:12,fontSize:11}}>{children}</div>}
const card:React.CSSProperties={background:"white",border:"1px solid #e8e3da",borderRadius:12,padding:17,boxShadow:"0 3px 14px rgba(0,0,0,.04)"};const sectionTitle:React.CSSProperties={margin:0,color:GREEN,fontFamily:"'Playfair Display', serif",fontSize:18};const sub:React.CSSProperties={margin:"4px 0 0",color:"#777",fontSize:10,lineHeight:1.5};const input:React.CSSProperties={border:"1px solid #d8dfda",borderRadius:7,padding:"9px 10px",fontSize:11,background:"white"};const th:React.CSSProperties={padding:"9px 8px",textAlign:"left",color:"#777",fontSize:9,textTransform:"uppercase"};const td:React.CSSProperties={padding:"10px 8px",fontSize:10,color:"#444",verticalAlign:"middle"};const small:React.CSSProperties={display:"block",color:"#888",fontSize:8,marginTop:2};const mini=(color:string):React.CSSProperties=>({display:"inline-flex",alignItems:"center",gap:3,border:"1px solid #d9dfdb",background:"white",color,borderRadius:6,padding:"5px 7px",fontSize:9,fontWeight:800,cursor:"pointer"});const action=(color:string):React.CSSProperties=>({display:"inline-flex",alignItems:"center",gap:4,border:`1px solid ${color}33`,background:`${color}0d`,color,borderRadius:6,padding:"6px 8px",fontSize:9,fontWeight:800,cursor:"pointer"});const tabBtn=(active:boolean):React.CSSProperties=>({border:`1px solid ${active?GREEN:"#d9dfdb"}`,background:active?GREEN:"white",color:active?"white":GREEN,borderRadius:8,padding:"8px 11px",fontSize:10,fontWeight:800,cursor:"pointer"});const ghost:React.CSSProperties={display:"inline-flex",alignItems:"center",gap:4,border:"1px solid rgba(255,255,255,.28)",background:"rgba(255,255,255,.08)",color:"white",borderRadius:7,padding:"7px 9px",fontSize:9,fontWeight:800,cursor:"pointer"};const primaryLink:React.CSSProperties={display:"inline-flex",alignItems:"center",gap:4,background:GREEN,color:"white",borderRadius:7,padding:"8px 11px",fontSize:10,fontWeight:800,textDecoration:"none"};const secondaryLink:React.CSSProperties={...primaryLink,background:"white",color:GREEN,border:"1px solid #d5ded8"};const secondaryButton:React.CSSProperties={...secondaryLink,cursor:"pointer"};
