import { useEffect, useState } from "react";
import { Link, Navigate, useParams } from "react-router";
import { ArrowLeft, BadgeCheck, Printer, ShieldCheck } from "lucide-react";
import { useAdmin } from "../context/AdminContext";
import { fetchAllMatrimonials, MatrimonialProfile, MatrimonialReference } from "../lib/matrimonialStore";
import { BEHAVIOR_QUESTIONS } from "../lib/matrimonialCompatibility";

const GREEN="#1a4d2e", GOLD="#c8a04a";

export function AdminMatrimonialPrintPage(){
  const {isAdmin,role}=useAdmin();
  const allowed=["admin","super_admin","welfare_manager","matrimonial_manager"].includes(String(role||""));
  const {id}=useParams();
  const [profile,setProfile]=useState<MatrimonialProfile|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  useEffect(()=>{if(!isAdmin||!allowed||!id)return;(async()=>{try{const r=await fetchAllMatrimonials(1,100);const p=r.data.find(x=>x.id===id);if(!p)throw new Error("Candidate profile not found.");setProfile(p);}catch(e:any){setError(e?.message||"Could not load printable form.");}finally{setLoading(false);}})();},[id,isAdmin,allowed]);
  if(!isAdmin||!allowed)return <Navigate to="/admin" replace/>;
  if(loading)return <div style={{padding:60,textAlign:"center"}}>Loading official form...</div>;
  if(error||!profile)return <div style={{padding:50,color:"#b91c1c"}}>{error||"Profile not found."}</div>;
  const d=profile.profileData||{}, pref=profile.preferenceData||{}, privacy=profile.privacyData||{}, behavior=d.behavior||{};
  const references=(Array.isArray(d.references)?d.references:[]) as MatrimonialReference[];
  const timeline=d.marriageTimeline||formatTimeline(d.marriageTimelineValue,d.marriageTimelineUnit,d.marriageTimelineFlexibility);
  return <div style={{background:"#eee",minHeight:"100vh",padding:"20px",fontFamily:"Arial, sans-serif"}}>
    <div className="print-actions" style={{maxWidth:900,margin:"0 auto 12px",display:"flex",justifyContent:"space-between",gap:8}}><Link to="/admin/matrimonial" style={btn}><ArrowLeft size={14}/>Control Center</Link><button onClick={()=>window.print()} style={primary}><Printer size={14}/>Print / Save PDF</button></div>
    <article style={{maxWidth:900,margin:"0 auto",background:"white",padding:"38px 42px",boxShadow:"0 5px 25px rgba(0,0,0,.12)"}}>
      <header style={{borderBottom:`3px solid ${GOLD}`,paddingBottom:16,marginBottom:20,display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start"}}><div><div style={{color:GREEN,fontSize:24,fontWeight:800}}>Anjuman-e-Araian Faisalabad</div><div style={{fontSize:14,color:"#555",marginTop:3}}>Confidential Matrimonial Candidate Form</div><div style={{fontSize:10,color:"#888",marginTop:5}}>Authorized internal document · not for public distribution</div></div><div style={{textAlign:"right"}}><div style={{fontWeight:800,color:GREEN}}>{profile.profileCode}</div><div style={{fontSize:10,color:"#777",marginTop:4}}>Printed: {new Date().toLocaleString()}</div></div></header>
      <div style={{background:"#f5f8f6",border:`1px solid #d9e6dd`,padding:10,borderRadius:6,fontSize:10,color:"#56615a",marginBottom:18}}><ShieldCheck size={13} style={{verticalAlign:"-3px",marginRight:5}}/>Contains private candidate and reference information. Handle only within the authorized matrimonial process and according to recorded candidate/guardian consent.</div>
      <Section title="Candidate Identification"><Grid><Item k="Full Name" v={profile.name}/><Item k="Candidate Email" v={profile.email}/><Item k="Private Contact" v={profile.contact}/><Item k="Managed For" v={profile.relationToCandidate}/><Item k="Gender" v={profile.gender}/><Item k="Age" v={profile.age}/><Item k="Date of Birth" v={profile.dateOfBirth}/><Item k="Height" v={profile.heightCm?`${profile.heightCm} cm`:""}/><Item k="Marital Status" v={profile.maritalStatus}/><Item k="Candidate Consent" v={profile.candidateConsent?"Recorded":"Not recorded"}/></Grid></Section>
      <Section title="Location, Education & Career"><Grid><Item k="Country" v={profile.country}/><Item k="Province / State" v={profile.province}/><Item k="City" v={profile.city}/><Item k="Nationality" v={profile.nationality}/><Item k="Residence / Visa" v={profile.residenceStatus}/><Item k="Education" v={profile.education}/><Item k="Profession" v={profile.profession}/><Item k="Employment Type" v={profile.employmentType||d.employmentType}/><Item k="Employer Type" v={profile.employerType||d.employerType}/><Item k="Income Band" v={profile.incomeBand||d.incomeBand}/><Item k="Currency" v={profile.currency}/></Grid></Section>
      <Section title="Family, Lifestyle & Intentions"><Grid><Item k="Family Setup" v={d.familySetup}/><Item k="Sect" v={d.sect}/><Item k="Languages" v={Array.isArray(d.languages)?d.languages.join(", "):d.languages}/><Item k="Hobbies" v={d.hobbies}/><Item k="Marriage Timeline" v={timeline}/><Item k="Timeline Normalized" v={d.marriageTimelineDays?`${d.marriageTimelineDays} days`:""}/><Item k="Timeline Flexibility" v={d.marriageTimelineFlexibility}/><Item k="Relocation" v={d.relocation}/></Grid><Text k="Family Notes / Background" v={d.familyNotes||profile.familyBackground}/></Section>
      {Object.values(behavior).some((v:any)=>Number(v)>0)&&<Section title="Lifestyle & Behavior Compatibility Answers"><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:"7px 14px"}}>{BEHAVIOR_QUESTIONS.map(q=><BehaviorItem key={q.key} label={q.label} value={behavior[q.key]}/>)}</div><div style={{fontSize:8,color:"#777",marginTop:8,lineHeight:1.5}}>Self-reported lifestyle/communication preferences used as soft compatibility signals. They are not a psychological diagnosis or suitability guarantee.</div></Section>}
      <Section title="Partner Preferences"><Pref label="Age" data={pref.age}/><Pref label="Height" data={pref.height}/><Pref label="Education" data={pref.education}/><Pref label="Profession" data={pref.profession}/><Pref label="Country" data={pref.country}/><Pref label="City" data={pref.city}/><Pref label="Marital Status" data={pref.maritalStatus}/><Pref label="Residence Status" data={pref.residenceStatus}/><Pref label="Family Setup" data={pref.familySetup}/><Pref label="Sect" data={pref.sect}/><Pref label="Relocation" data={pref.relocation}/><Pref label="Income" data={pref.income}/><Text k="Other Expectations" v={pref.notes||profile.requirements}/></Section>
      <Section title="References / Verification">{references.length?<div style={{display:"grid",gap:8}}>{references.map((r,index)=><div key={index} style={{border:"1px solid #e4e7e5",borderRadius:6,padding:9,pageBreakInside:"avoid"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><strong style={{color:GREEN,fontSize:10}}>Reference {index+1}: {r.name}</strong>{r.isMember&&<span style={{display:"inline-flex",alignItems:"center",gap:3,background:"#e7f7ec",color:"#166534",borderRadius:14,padding:"3px 6px",fontSize:8,fontWeight:800}}><BadgeCheck size={10}/>Anjuman Member {r.memberNo||""}</span>}</div><Grid><Item k="Profession" v={r.profession}/><Item k="Mobile" v={r.phone}/><Item k="City" v={r.city}/><Item k="Address / Area" v={r.address}/><Item k="Member Record" v={r.isMember?(r.memberName||r.name):"Non-member reference"}/></Grid></div>)}</div>:<div style={{fontSize:10,color:"#a16207",background:"#fff7ed",padding:8,borderRadius:6}}>References have not yet been recorded. Minimum two references are required on the updated workflow.</div>}</Section>
      <Section title="Privacy, Verification & Workflow"><Grid><Item k="Profile Status" v={profile.status}/><Item k="Payment Status" v={profile.paymentStatus}/><Item k="Verification" v={profile.verificationStatus}/><Item k="Profile & Match Readiness" v={`${profile.profileCompleteness||0}%`}/><Item k="Private Matching" v={profile.showOnPortal?"Enabled":"Disabled"}/><Item k="Photo Privacy" v={privacy.photoVisibility}/><Item k="Contact Privacy" v={privacy.contactVisibility}/><Item k="Application Source" v={profile.applicationSource}/><Item k="Last Profile Email" v={profile.lastProfileEmailAt?new Date(profile.lastProfileEmailAt).toLocaleString():"Not sent"}/></Grid><Text k="Admin / Manager Note" v={profile.adminNote}/></Section>
      {profile.photoUrl&&<Section title="Candidate Photo (Confidential)"><img src={profile.photoUrl} alt="Candidate" style={{width:130,height:160,objectFit:"cover",border:"1px solid #ddd",borderRadius:4}}/></Section>}
      <footer style={{borderTop:"1px solid #ddd",marginTop:26,paddingTop:14,fontSize:9,color:"#777",display:"flex",justifyContent:"space-between"}}><span>Confidential · Anjuman-e-Araian Faisalabad Matrimonial Service</span><span>{profile.profileCode}</span></footer>
    </article>
    <style>{`@media print{body{background:white!important}.print-actions{display:none!important}article{box-shadow:none!important;max-width:none!important;padding:20px 25px!important}@page{size:A4;margin:12mm}}`}</style>
  </div>;
}
function formatTimeline(value:any,unit:any,flexibility:any){if(!value)return "";const n=Number(value);const u=String(unit||"months");return `Within ${n} ${u}${flexibility==="flexible"?" (flexible)":""}`;}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={{marginBottom:20,pageBreakInside:"avoid"}}><h2 style={{fontSize:13,color:GREEN,borderBottom:"1px solid #ddd",paddingBottom:5,margin:"0 0 10px"}}>{title}</h2>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:"8px 14px",marginTop:7}}>{children}</div>}
function Item({k,v}:{k:string;v:any}){if(v===undefined||v===null||String(v).trim()==="")return null;return <div><div style={{fontSize:8,color:"#888",textTransform:"uppercase",fontWeight:700}}>{k}</div><div style={{fontSize:10,color:"#222",marginTop:2,wordBreak:"break-word"}}>{String(v).replace(/_/g," ")}</div></div>}
function BehaviorItem({label,value}:{label:string;value:any}){const n=Number(value||0);if(n<1||n>5)return null;return <div style={{border:"1px solid #eee",borderRadius:5,padding:6}}><div style={{fontSize:8,color:"#777",fontWeight:700}}>{label}</div><div style={{fontSize:10,color:GREEN,fontWeight:800,marginTop:2}}>{n}/5</div></div>}
function Text({k,v}:{k:string;v:any}){if(!v)return null;return <div style={{marginTop:9}}><div style={{fontSize:8,color:"#888",textTransform:"uppercase",fontWeight:700}}>{k}</div><div style={{fontSize:10,lineHeight:1.55,color:"#333",whiteSpace:"pre-wrap",marginTop:2}}>{String(v)}</div></div>}
function Pref({label,data}:{label:string;data:any}){if(!data||typeof data!=="object")return null;const primary=Array.isArray(data.primary)?data.primary.join(", "):"",secondary=Array.isArray(data.secondary)?data.secondary.join(", "):"",acceptable=Array.isArray(data.acceptable)?data.acceptable.join(", "):"";const range=data.min||data.max?`${data.min||"Any"} – ${data.max||"Any"}`:"";const income=data.minimum?`Minimum ${data.minimum}`:"";if(!primary&&!secondary&&!acceptable&&!range&&!income)return null;return <div style={{display:"grid",gridTemplateColumns:"130px 1fr",gap:8,borderBottom:"1px dotted #ddd",padding:"5px 0",fontSize:9}}><strong style={{color:GREEN}}>{label}</strong><span>{range||income||[primary&&`Primary: ${primary}`,secondary&&`Secondary: ${secondary}`,acceptable&&`Acceptable: ${acceptable}`].filter(Boolean).join(" · ")} {data.importance?`[${String(data.importance).replace(/_/g," ")}]`:""}</span></div>}
const btn:React.CSSProperties={display:"inline-flex",alignItems:"center",gap:5,background:"white",color:GREEN,border:"1px solid #ccd8cf",borderRadius:7,padding:"9px 12px",textDecoration:"none",fontSize:11,fontWeight:800};const primary:React.CSSProperties={...btn,background:GREEN,color:"white",cursor:"pointer"};
