-- Deprecated before production application.
-- The live database does not contain the lifecycle columns introduced by the earlier application build.
-- Keep this migration intentionally empty so deploys remain compatible with the existing production schema.
