import jwt from "jsonwebtoken";
import prisma from "../lib/prisma";
import { emailFrame, sendEmail } from "../lib/email";
import { matrimonialCompatibility } from "../lib/matrimonialCompatibility";
import { createMatrimonialProfilePdf } from "../lib/matrimonialPdf";

function clean(v:any){return String(v??"").trim();}
function digits(v:any){return clean(v).replace(/\D/g,"");}
function jsonObject(v:any){return v&&typeof v==="object"&&!Array.isArray(v)?v:{};}
function code(id:string){return `AAF-MAT-${String(id).replace(/-/g,"").slice(0,8).toUpperCase()}`;}
function band(score:number){return score>=80?"excellent_80":score>=70?"strong_70":score>=50?"relevant_50":"below_50";}
function above(value:string){return value!=="below_50";}
function bodyOf(req:any){if(!req?.body)return{};if(typeof req.body==="string"){try{return JSON.parse(req.body)}catch{return{}}}return req.body;}
function auth(req:any){const h=clean(req.headers?.authorization);if(!h.startsWith("Bearer ")||!process.env.JWT_SECRET)throw Object.assign(new Error("Authentication required"),{status:401});try{return jwt.verify(h.slice(7),process.env.JWT_SECRET) as any}catch{throw Object.assign(new Error("Your session has expired. Please sign in again."),{status:401})}}

async function account(user:any){const rows=user?.id?await prisma.$queryRaw<any[]>`SELECT "id","email" FROM "AuthUser" WHERE "id"=${String(user.id)} LIMIT 1`:[];return rows[0]||null;}
async function profile(id:string){const rows=await prisma.$queryRaw<any[]>`SELECT m.*,a."email" AS "accountEmail" FROM "Matrimonial" m LEFT JOIN "AuthUser" a ON a."id"=m."authUserId" WHERE m."id"=${id} LIMIT 1`;if(!rows[0])return null;const p=rows[0];return {...p,profileCode:code(p.id),profileData:jsonObject(p.profileData),preferenceData:jsonObject(p.preferenceData),privacyData:jsonObject(p.privacyData),email:clean(p.email)||clean(p.accountEmail)};}
async function audit(user:any,action:string,profileId:string,details:any){await prisma.$executeRaw`INSERT INTO "MatrimonialAuditLog" ("profileId","action","actorId","actorName","actorRole","details") VALUES (${profileId},${action},${user.id||null},${user.email||null},${user.role||"member"},${JSON.stringify(details||{})}::jsonb)`;}

async function verifiedReferences(input:any[]){const refs=(Array.isArray(input)?input:[]).slice(0,8).map(r=>({name:clean(r?.name),profession:clean(r?.profession),phone:clean(r?.phone),city:clean(r?.city),address:clean(r?.address)}));if(refs.length<2)throw Object.assign(new Error("At least two references are required."),{status:400});const out:any[]=[];for(let i=0;i<refs.length;i++){const r=refs[i];if(!r.name||!r.profession||digits(r.phone).length<10||(!r.city&&!r.address))throw Object.assign(new Error(`Reference ${i+1} is incomplete.`),{status:400});const phone10=digits(r.phone).slice(-10);const rows=await prisma.$queryRaw<any[]>`SELECT "id","memberNo","fullName","phone","city" FROM "Member" WHERE "status"='approved' AND (right(regexp_replace(COALESCE("phone",''),'\\D','','g'),10)=${phone10} OR lower(trim("fullName"))=lower(${r.name})) ORDER BY CASE WHEN right(regexp_replace(COALESCE("phone",''),'\\D','','g'),10)=${phone10} THEN 0 ELSE 1 END LIMIT 1`;const m=rows[0];out.push({...r,isMember:Boolean(m),memberId:m?.id||null,memberNo:m?.memberNo||null,memberName:m?.fullName||null,memberPhone:m?.phone||null,memberCity:m?.city||null,memberVerified:Boolean(m),verifiedAt:m?new Date().toISOString():null});}return out;}

async function sendPacket(p:any){if(!p.email)return{sent:false,reason:"email_missing"};const pdf=createMatrimonialProfilePdf(p);return sendEmail(p.email,`Your confidential matrimonial profile - ${p.profileCode}`,emailFrame("Matrimonial Profile Saved",`<p>Dear ${p.name||"Candidate"},</p><p>Your confidential profile <strong>${p.profileCode}</strong> has been saved. The attached A4 PDF is your private official record.</p><p>Current profile and matching readiness: <strong>${Number(p.profileCompleteness||0)}%</strong>.</p><p>Your identity, photo and contact remain protected by the consent workflow.</p>`),[{filename:`${p.profileCode}-confidential-profile.pdf`,content:pdf,contentType:"application/pdf"}]);}
async function matchEmail(p:any,score:number,up:boolean){if(!p.email)return{sent:false,reason:"email_missing"};const title=up?"A private compatibility match is available":"Your compatibility match status was updated";const text=up?`A private compatibility result of <strong>${score}%</strong> is available for profile <strong>${p.profileCode}</strong>. Sign in to review the anonymized result. No name, photo or contact of the other party is included in this alert.`:`A previously notified compatibility result for <strong>${p.profileCode}</strong> changed after profile/preferences were updated and is now below the 50% notification threshold. No private information has been released.`;return sendEmail(p.email,title,emailFrame(title,`<p>${text}</p>`));}

async function recalc(p:any,user:any){if(!(p.status==="approved"&&p.showOnPortal===true&&p.isActive!==false))return{checked:0,notifications:0};const targets=await prisma.$queryRaw<any[]>`SELECT m.*,a."email" AS "accountEmail" FROM "Matrimonial" m LEFT JOIN "AuthUser" a ON a."id"=m."authUserId" WHERE m."id"<>${p.id} AND m."isActive"=true AND m."status"='approved' AND m."showOnPortal"=true AND m."gender"<>${p.gender} LIMIT 300`;let notifications=0;for(const raw of targets){const t={...raw,profileCode:code(raw.id),profileData:jsonObject(raw.profileData),preferenceData:jsonObject(raw.preferenceData),privacyData:jsonObject(raw.privacyData),email:clean(raw.email)||clean(raw.accountEmail)};const c=matrimonialCompatibility(p,t);const score=Number(c.mutualScore||0),next=band(score);const a=p.id<t.id?p.id:t.id,b=p.id<t.id?t.id:p.id;const previous=await prisma.$queryRaw<any[]>`SELECT * FROM "MatrimonialMatchAlert" WHERE "profileAId"=${a} AND "profileBId"=${b} LIMIT 1`;const old=previous[0]?.lastBand||"below_50",up=!above(old)&&above(next),down=above(old)&&!above(next);if(previous.length)await prisma.$executeRaw`UPDATE "MatrimonialMatchAlert" SET "lastScore"=${score},"lastBand"=${next},"lastNotifiedAt"=CASE WHEN ${up||down} THEN CURRENT_TIMESTAMP ELSE "lastNotifiedAt" END,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${previous[0].id}`;else await prisma.$executeRaw`INSERT INTO "MatrimonialMatchAlert" ("profileAId","profileBId","lastScore","lastBand","lastNotifiedAt") VALUES (${a},${b},${score},${next},${up?new Date():null})`;if(up||down){const [one,two]=await Promise.all([matchEmail(p,score,up),matchEmail(t,score,up)]);notifications+=Number(Boolean(one.sent))+Number(Boolean(two.sent));await audit(user,up?"compatibility_threshold_notification":"compatibility_threshold_withdrawn",p.id,{counterpartProfileId:t.id,score,candidateEmailSent:Boolean(one.sent),counterpartEmailSent:Boolean(two.sent)});}}await prisma.$executeRaw`UPDATE "Matrimonial" SET "lastMatchedAt"=CURRENT_TIMESTAMP,"lastMatchNotificationAt"=CASE WHEN ${notifications>0} THEN CURRENT_TIMESTAMP ELSE "lastMatchNotificationAt" END WHERE "id"=${p.id}`;return{checked:targets.length,notifications};}

export async function matrimonialSelfSync(req:any,res:any){try{const user=auth(req);const a=await account(user);if(!a?.email)return res.status(400).json({error:"A verified account email is required."});const url=new URL(String(req.url||"/api/matrimonial-self-sync"),"http://localhost");const b=bodyOf(req);const action=clean(b.action||url.searchParams.get("action"));const requested=clean(b.profileId||url.searchParams.get("profileId"));if(action==="meta"){let refs:any[]=[];if(requested){const p=await profile(requested);if(p&&p.authUserId===user.id)refs=Array.isArray(p.profileData?.references)?p.profileData.references:[];}return res.json({email:a.email,references:refs});}if(action!=="sync_profile")return res.status(400).json({error:"Unsupported action"});if(!requested)return res.status(400).json({error:"Profile ID is required"});const p=await profile(requested);if(!p)return res.status(404).json({error:"Candidate profile not found"});if(p.authUserId!==user.id)return res.status(403).json({error:"This candidate profile does not belong to your account."});const refs=await verifiedReferences(b.references);const nextData={...jsonObject(p.profileData),references:refs};await prisma.$executeRaw`UPDATE "Matrimonial" SET "email"=${String(a.email).toLowerCase()},"profileData"=${JSON.stringify(nextData)}::jsonb,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${requested}`;await audit(user,"candidate_self_references_synced",requested,{references:refs.map(r=>({name:r.name,phone:r.phone,isMember:r.isMember,memberNo:r.memberNo}))});const updated=await profile(requested);const mail=await sendPacket(updated);if(mail.sent)await prisma.$executeRaw`UPDATE "Matrimonial" SET "lastProfileEmailAt"=CURRENT_TIMESTAMP WHERE "id"=${requested}`;const matching=await recalc(updated,user);return res.json({email:a.email,references:refs,profile:updated,packet:mail,matching});}catch(e:any){console.error("matrimonial self sync error",e);return res.status(Number(e?.status||500)).json({error:e?.message||"Matrimonial verification sync failed"});}}
